-- MySQL Script generated by MySQL Workbench
-- Tue Oct  2 15:26:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `viewgroup` DEFAULT CHARACTER SET utf8 ;
USE `viewgroup` ;

-- -----------------------------------------------------
-- Table `mydb`.`grupo_invest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup`.`grupo_invest` (
  `id_grupo_invest` INT NOT NULL,
  `email_grupo` VARCHAR(45) NULL,
  `telefo_grupo` VARCHAR(45) NULL,
  `direcc_grupo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_grupo_invest`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup`.`producto` (
  `id_produc` INT NOT NULL,
  `fecha_de_produc` DATE NULL,
  `estado_produc` TINYINT NULL,
  `lugar_produc` VARCHAR(45) NULL,
  `publico_produc` TINYINT NULL,
  `producto_pricipal_fk_id_producto` INT NOT NULL,
  `fk_id_grupo_invest` INT  NULL,
  PRIMARY KEY (`id_produc`),
  INDEX `fk_eventos_proyecto_eventos_proyecto1_idx` (`producto_pricipal_fk_id_producto` ASC),
  INDEX `fk_producto_grupo_invest1_idx` (`fk_id_grupo_invest` ASC),
  CONSTRAINT `fk_eventos_proyecto_eventos_proyecto1`
    FOREIGN KEY (`producto_pricipal_fk_id_producto`)
    REFERENCES `mydb`.`producto` (`id_produc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_grupo_invest1`
    FOREIGN KEY (`fk_id_grupo_invest`)
    REFERENCES `mydb`.`grupo_invest` (`id_grupo_invest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plantilla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup`.`plantilla` (
  `id_plantilla` INT NOT NULL,
  `nom_plantilla` VARCHAR(45) NULL,
  PRIMARY KEY (`id_plantilla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagina_web`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup`.`pagina_web` (
  `id_pagina` INT NOT NULL,
  `url_pagina` VARCHAR(45) NULL,
  `fk_id_plantilla` INT NOT NULL,
  `grupo_invest_id_grupo_invest` INT NOT NULL,
  PRIMARY KEY (`id_pagina`),
  INDEX `fk_pagina_web_plantilla1_idx` (`fk_id_plantilla` ASC),
  INDEX `fk_pagina_web_grupo_invest1_idx` (`grupo_invest_id_grupo_invest` ASC),
  CONSTRAINT `fk_pagina_web_plantilla1`
    FOREIGN KEY (`fk_id_plantilla`)
    REFERENCES `mydb`.`plantilla` (`id_plantilla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagina_web_grupo_invest1`
    FOREIGN KEY (`grupo_invest_id_grupo_invest`)
    REFERENCES `mydb`.`grupo_invest` (`id_grupo_invest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup`.`permisos` (
  `id_permisos` INT NOT NULL,
  `nom_perimisos` VARCHAR(45) NULL,
  PRIMARY KEY (`id_permisos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup`.`roles` (
  `id_rol` INT NOT NULL,
  `nom_rol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles_permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup`.`roles_permisos` (
  `roles_id_rol` INT NOT NULL,
  `permisos_id_permisos` INT NOT NULL,
  `fecha_permiso` VARCHAR(45) NULL,
  PRIMARY KEY (`roles_id_rol`, `permisos_id_permisos`),
  INDEX `fk_roles_has_permisos_permisos1_idx` (`permisos_id_permisos` ASC),
  INDEX `fk_roles_has_permisos_roles1_idx` (`roles_id_rol` ASC),
  UNIQUE INDEX `permisos_id_permisos_UNIQUE` (`permisos_id_permisos` ASC),
  CONSTRAINT `fk_roles_has_permisos_roles1`
    FOREIGN KEY (`roles_id_rol`)
    REFERENCES `mydb`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_has_permisos_permisos1`
    FOREIGN KEY (`permisos_id_permisos`)
    REFERENCES `mydb`.`permisos` (`id_permisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup`.`usuario` (
  `id_usuario` INT NOT NULL,
  `informa_extra_usuario` VARCHAR(45) NULL,
  `roles_id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_roles1_idx` (`roles_id_rol` ASC),
  CONSTRAINT `fk_usuario_roles1`
    FOREIGN KEY (`roles_id_rol`)
    REFERENCES `mydb`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`informacion_integrantes_proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup`.`informacion_integrantes_proyecto` (
  `pk_fk_id_evento` INT NOT NULL,
  `pk_fk_id_usuario` INT NOT NULL,
  `funcion_miembro` INT NULL,
  `Descrip_miembro` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_fk_id_evento`, `pk_fk_id_usuario`),
  INDEX `fk_eventos_proyecto_has_usuario_usuario1_idx` (`pk_fk_id_usuario` ASC),
  INDEX `fk_eventos_proyecto_has_usuario_eventos_proyecto1_idx` (`pk_fk_id_evento` ASC),
  CONSTRAINT `fk_eventos_proyecto_has_usuario_eventos_proyecto1`
    FOREIGN KEY (`pk_fk_id_evento`)
    REFERENCES `mydb`.`producto` (`id_produc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_proyecto_has_usuario_usuario1`
    FOREIGN KEY (`pk_fk_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup`.`tipo_actividad` (
  `id_tipo_actividad` INT NOT NULL,
  `nom_tipo_actividad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_actividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup`.`Actividad` (
  `id_Actividad` INT NOT NULL,
  `fk_id_produc` INT NULL,
  `fk_id_tipo_actividad` INT NOT NULL,
  `nom_actividad` VARCHAR(45) NULL,
  `descripcion_actividad` VARCHAR(45) NULL,
  `fecha_actividad` DATE NULL,
  `entregas_actividad` VARCHAR(45) NULL,
  `conclusion_actividad` VARCHAR(45) NULL,
  `avanze_actividad` VARCHAR(45) NULL,
  `apreciacion_actividad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Actividad`),
  INDEX `fk_Actividad_eventos_proyecto1_idx` (`fk_id_produc` ASC),
  INDEX `fk_Actividad_tipo_actividad1_idx` (`fk_id_tipo_actividad` ASC),
  CONSTRAINT `fk_Actividad_eventos_proyecto1`
    FOREIGN KEY (`fk_id_produc`)
    REFERENCES `mydb`.`producto` (`id_produc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_tipo_actividad1`
    FOREIGN KEY (`fk_id_tipo_actividad`)
    REFERENCES `mydb`.`tipo_actividad` (`id_tipo_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actividad_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup`.`Actividad_has_usuario` (
  `pk_fk_id_Actividad` INT NOT NULL,
  `pk_fk_id_usuario` INT NOT NULL,
  `fecha_asigna` DATE NULL,
  `descripcion_tarea` VARCHAR(45) NULL,
  `asistencia` TINYINT NULL,
  PRIMARY KEY (`pk_fk_id_Actividad`, `pk_fk_id_usuario`),
  INDEX `fk_Actividad_has_usuario_usuario1_idx` (`pk_fk_id_usuario` ASC),
  INDEX `fk_Actividad_has_usuario_Actividad1_idx` (`pk_fk_id_Actividad` ASC),
  CONSTRAINT `fk_Actividad_has_usuario_Actividad1`
    FOREIGN KEY (`pk_fk_id_Actividad`)
    REFERENCES `mydb`.`Actividad` (`id_Actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_has_usuario_usuario1`
    FOREIGN KEY (`pk_fk_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diseno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup`.`Diseno` (
  `id_diseno` INT NOT NULL,
  `Color_diseno` VARCHAR(45) NULL,
  `fuente_letra` VARCHAR(45) NULL,
  `lugar_seccion` VARCHAR(45) NULL,
  `plantilla_id_plantilla` INT NOT NULL,
  PRIMARY KEY (`id_diseno`, `plantilla_id_plantilla`),
  INDEX `fk_Diseno_plantilla1_idx` (`plantilla_id_plantilla` ASC),
  CONSTRAINT `fk_Diseno_plantilla1`
    FOREIGN KEY (`plantilla_id_plantilla`)
    REFERENCES `mydb`.`plantilla` (`id_plantilla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fases_cronogra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup`.`fases_cronogra` (
  `id_fases_cronogra` INT NOT NULL,
  `nom_fases_cronogra` VARCHAR(45) NULL,
  `producto_id_produc` INT NOT NULL,
  PRIMARY KEY (`id_fases_cronogra`, `producto_id_produc`),
  INDEX `fk_fases_cronogra_producto1_idx` (`producto_id_produc` ASC),
  CONSTRAINT `fk_fases_cronogra_producto1`
    FOREIGN KEY (`producto_id_produc`)
    REFERENCES `mydb`.`producto` (`id_produc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`soporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup`.`soporte` (
  `id_soporte` INT NOT NULL,
  `url_imagene` VARCHAR(45) NULL,
  `pk_fk_id_produc` INT NOT NULL,
  PRIMARY KEY (`id_soporte`, `pk_fk_id_produc`),
  INDEX `fk_soporte_producto1_idx` (`pk_fk_id_produc` ASC),
  CONSTRAINT `fk_soporte_producto1`
    FOREIGN KEY (`pk_fk_id_produc`)
    REFERENCES `mydb`.`producto` (`id_produc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viewgroup`.`vistas` (
  `id_vistas` INT NOT NULL,
  `nom_vistas` VARCHAR(45) NULL,
  `permisos_id_permisos` INT NOT NULL,
  PRIMARY KEY (`id_vistas`),
  INDEX `fk_vistas_permisos1_idx` (`permisos_id_permisos` ASC),
  CONSTRAINT `fk_vistas_permisos1`
    FOREIGN KEY (`permisos_id_permisos`)
    REFERENCES `mydb`.`permisos` (`id_permisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;